### ISSUE TITLE
(Discord Server) Ban Appeal - Kolkies

### ISSUE THREAD

**Issue by stijnvdkolk** [20Koen02/Gideon#1]
Beste Koen,
Hierbij wil ik graag een unban aanvragen. Ik ga je proberen te overtuigen.

Ik keek of Gideon public was, dat had ik eigenlijk niet moeten doen. Toen ik erachter kwam dat het kon, wilde ik jou informeren. Alleen mijn ouders vonden dat ik moest stoppen.
Toen ben jij denk ik door iemand die in de test server waar k m naar toe had invited geroepen.

Sorry dat ik toen jij mij mentionde ik niet reageerde, ik lag te slapen.

Ik hoop dat je dit leest en dat ik dus ook snel een reactie krijg.
Ik hoop ook dat je dit niet meteen verwijderd zonder te reageren.

Mvg,
Kolkies

**Comment by 20Koen02** [comment]
Sorry dat het zo lang duurde,
Dit was deels ook mijn fout. Ik was vergeten mijn bot op privé te zetten.
Om dit conflict op te lossen heb ik jou van mijn ban lijst af gehaald. 😄 
Welkom terug, Kolkies. https://discord.gg/9ff7HwU

**Comment by stijnvdkolk** [comment]
Bedankt.
